### ISSUE TITLE
Announcement Image Height 100%

### ISSUE THREAD

**Issue by EvanHerman** [EvanHerman/timeline-express#20]
Announcement images on mobile devices get squished. Set height 100% on them to work around this issue.

Add:

``` css
img.announcement-banner-image {
      height: 100%;
      width: 100%;
}
```

Reference:
https://wordpress.org/support/topic/images-distorted-in-mobile-view?replies=2#post-8668344
